"""added post_created_on field into post model

Revision ID: 2fd5dbf3d7f3
Revises: 107964c9efb5
Create Date: 2020-02-21 18:16:43.629232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd5dbf3d7f3'
down_revision = '107964c9efb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_on')
    # ### end Alembic commands ###
