"""added is_active field in blog model

Revision ID: b24b3decfed2
Revises: f2c07ef0900a
Create Date: 2020-02-21 16:31:13.058358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24b3decfed2'
down_revision = 'f2c07ef0900a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'is_active')
    # ### end Alembic commands ###
