"""added date_of_creation field in blog model

Revision ID: f2c07ef0900a
Revises: 2b4c762e502b
Create Date: 2020-02-21 16:29:12.857572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c07ef0900a'
down_revision = '2b4c762e502b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('date_of_creation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'date_of_creation')
    # ### end Alembic commands ###
